routes/admin.php
<?php

/*
 * Routing khusus admin panel
 */
Route::group(['prefix' => 'administrator', 'middleware' => ['globalvar', 'admin.panel'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('kegiatan-warga/get/images', 'Gallery\GalleryController@getImages')->name('gallery.get.images');
    Route::post('kegiatan-warga/store/images', 'Gallery\GalleryController@storeImages')->name('gallery.store.images');
    Route::post('kegiatan-warga/delete/images', 'Gallery\GalleryController@deleteImages')->name('gallery.delete.images');
    Route::resource('/', 'Dashboard\DashboardController');
    Route::resource('config', 'Config\ConfigController');
    Route::resource('seo', 'Config\SeoController');
    Route::resource('contact', 'Config\ContactController');
    Route::resource('logo', 'Config\LogoController');
    Route::resource('user', 'Config\UserController');
    Route::resource('slider', 'Slider\SliderController');
    Route::resource('kontak', 'ContactUs\ContactUsController')->names([
        'index' => 'contactus.index',
        'create' => 'contactus.create',
        'store' => 'contactus.store',
        'show' => 'contactus.show',
        'edit' => 'contactus.edit',
        'update' => 'contactus.update',
        'destroy' => 'contactus.destroy',
    ])->parameters(['kontak' => 'contactus']);
    Route::resource('produk-warga', 'Merchandise\MerchandiseController')->names([
        'index' => 'merchandise.index',
        'create' => 'merchandise.create',
        'store' => 'merchandise.store',
        'show' => 'merchandise.show',
        'edit' => 'merchandise.edit',
        'update' => 'merchandise.update',
        'destroy' => 'merchandise.destroy',
    ])->parameters(['produk-warga' => 'merchandise']);
    Route::resource('kegiatan-warga', 'Gallery\GalleryController')->names([
        'index' => 'gallery.index',
        'create' => 'gallery.create',
        'store' => 'gallery.store',
        'show' => 'gallery.show',
        'edit' => 'gallery.edit',
        'update' => 'gallery.update',
        'destroy' => 'gallery.destroy',
    ])->parameters(['kegiatan-warga' => 'gallery']);
    Route::resource('berita', 'News\NewsController')->names([
        'index' => 'news.index',
        'create' => 'news.create',
        'store' => 'news.store',
        'show' => 'news.show',
        'edit' => 'news.edit',
        'update' => 'news.update',
        'destroy' => 'news.destroy',
    ])->parameters(['berita' => 'news']);

    Route::resource('informasi', 'Article\ArticleController')->names([
        'index' => 'article.index',
        'create' => 'article.create',
        'store' => 'article.store',
        'show' => 'article.show',
        'edit' => 'article.edit',
        'update' => 'article.update',
        'destroy' => 'article.destroy',
    ])->parameters(['informasi' => 'article']);
    Route::get('informasi/image/get',     'Article\ImageController@getImage')->name('article.get_image');
    Route::post('informasi/image/store',  'Article\ImageController@storeImage')->name('article.store_image');
    Route::post('informasi/image/delete', 'Article\ImageController@deleteImage')->name('article.delete_image');

    Route::get('signout', 'AuthController@signout')->name('signout');
});

Route::group(['prefix' => 'auth', 'namespace' => 'Admin'], function () {
    Route::get('admin', 'AuthController@index')->name('login.admin');
    Route::post('admin', 'AuthController@store')->name('auth.admin');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Frontend', 'as' => 'frontend.', 'middleware' => ['globalvar']], function() {
    Route::get('/', 'Home\HomeController@index')->name('home');
    Route::get('berita', 'News\NewsController@index')->name('news');
    Route::get('berita/{slug}', 'News\NewsController@detail')->name('news.detail');
    Route::get('kegiatan-warga', 'Event\EventController@index')->name('activities');
    Route::get('kegiatan-warga/{slug}', 'Event\EventController@detail')->name('activities.detail');
    Route::get('kontak', 'Contact\ContactController@index')->name('contact');
    Route::get('produk-warga', 'Merchandise\MerchandiseController@index')->name('merchandise');
    Route::get('produk-warga/{slug}', 'Merchandise\MerchandiseController@detail')->name('merchandise.detail');
    Route::get('informasi', 'Information\InformationController@index')->name('informasi');
    Route::get('informasi/{id}', 'Information\InformationController@show')->name('informasi.detail');
    Route::get('cache', function() {
        $artisan = Artisan::call('view:cache');
    	 // $artisan = Artisan::call('migrate');

    	$artisan = Artisan::call('view:clear');
    	echo "Done";
    });
});

app/Http/Controllers/Admin/Article/ArticleController.php
<?php

namespace App\Http\Controllers\Admin\Article;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Article;
use App\Models\ArticleImage;
use Str;
use File;
use Storage;

class ArticleController extends Controller
{
    protected $article;
    protected $articleImage;
    public function __construct()
    {
        $this->article      = new Article;
        $this->articleImage = new ArticleImage;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $request->session()->forget('admin'.auth()->user()->id.'.article_image');
        $request->session()->forget('admin'.auth()->user()->id.'.article_image_delete');
        $data['models'] = Article::all();
        return view('admin.article.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        // if ($request->session()->get('admin'.auth()->user()->id.'.image_product') == null) {
        //     $file = glob('storage/tmp/product/*');
        //     foreach ($file as $key => $value) {
        //         if (is_file($value)) {
        //             unlink("{$value}");
        //         }
        //     }
        // }
        return view('admin.article.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'banner' => 'required'
        ]);

        $image = $request->file('banner');
        $originalName = $image->getClientOriginalName();
        $extFile = $image->getClientOriginalExtension();

        $create = [
            'name' => $request->name,
            'slug' => Str::slug($request->name),
            'description' => $request->description,
            'banner' => $image->storeAs('article', ucwords(Str::slug($request->name)).'.'.$extFile),
            'status' => $request->status ? true : false
        ];

        if ($article = $this->article->create($create)) {
            // setelah menyimpan data product kemudian ambil id product

            $destinationPath = 'image/article/';
            $sourcePath = 'tmp/article/';

            //Ambil data image pada session
            $imageFromSession = $request->session()->get('admin'.auth()->user()->id.'.article_image');
            if ($imageFromSession) {
                // jika datanya ada maka jadikan string
                foreach ($imageFromSession as $key => $image) {
                    // old path & name image product
                    $oldPath = $sourcePath. $image->name;
                    // new path & name image product
                    $newPath = $destinationPath.$image->name;

                    $articleImage               = new ArticleImage;
                    $articleImage->article_id   = $article->id;
                    $articleImage->image        = $newPath;
                    $articleImage->save();

                    Storage::move($oldPath, $newPath);
                }
            }

            return json_encode(['status' => true, 'response' => ['status' => 'Success', 'msg' => 'Data product berhasil di tambahkan', 'url' => route('admin.article.index')]]);
        }
        return json_encode(['status' => false, 'response' => ['status' => 'Error', 'Terjadi kesalahan, harap ulangi beberapa saat lagi!']]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Article $article)
    {
        $request->session()->forget('admin'.auth()->user()->id.'.article_image');
        $request->session()->forget('admin'.auth()->user()->id.'.article_image_delete');

        $articleImage = ArticleImage::where('article_id', $article->id)->get();
        foreach ($articleImage as $key => $data) {
            $path = $data->image;
            $key = explode('article'.auth()->user()->id.'-', $path);
            $file = explode('image/article', $path);
            $saveImageToSession = (object)['name' => $file[1], 'key' => $key[1], 'option' => 'edit', 'id' => $data->id];
            $request->session()->push('admin'.auth()->user()->id.'.article_image', $saveImageToSession);
        }
        // dd(session()->get('admin'.auth()->user()->id.'.article_image_delete')); exit;
        $data['model'] = $article;
        return view('admin.article.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $request->validate([
            'name'          => 'required',
            'description'   => 'required',
        ]);

        if ($request->hasFile('banner')) {

            if (Storage::exists($article->banner)) {
                Storage::delete($article->banner);
            }

            $fields = [
                'name' => $request->name,
                'slug' => Str::slug($request->name),
                'description' => $request->description,
                'banner' => $request->file('banner')->storeAs('article', Str::slug($request->name).'.'.$request->file('banner')->getClientOriginalExtension()),
                'status' => $request->status ? true : false
            ];
            $update = $article->update($fields);
        } else {
            $fields = [
                'name' => $request->name,
                'slug' => Str::slug($request->name),
                'description' => $request->description,
                'status' => $request->status ? true : false
            ];

            $update = $article->update($fields);
        }

        if ($update) {
            $destinationPath = 'image/article';
            $sourcePath = 'tmp/article';

            $getImageFromSession = $request->session()->get('admin'.auth()->user()->id.'.article_image');
            if ($getImageFromSession) {

                foreach ($getImageFromSession as $key => $data) {
                    if ($data->option == 'create') {
                        $oldPath = $sourcePath. $data->image;
                        $newPath = $destinationPath. $data->image;

                        $articleImage = new ArticleImage;
                        $articleImage->article_id = $article->id;
                        $articleImage->image = $newPath;
                        $articleImage->save();

                        Storage::move($oldPath, $newPath);
                    }
                }
            }

            $deleteImageFromSession = $request->session()->get('admin' . auth()->user()->id . '.article_image_delete');
            if (deleteImageFromSession) {
                foreach ($deleteImageFromSession as $key => $image) {
                    $path = public_path('storage/image/article/'. $image->delete);
                    if (file_exists($path)) {
                        unlink($path);
                    }

                    $articleImage = ArticleImage::findOrFail($image->id);
                    $articleImage->delete();
                }
            }

            return json_encode(['status' => true, 'response' => ['status' => 'Success', 'msg' => 'Informasi berhasil di tambahakan', 'url' => route('admin.article.index')]]);
        }

        return json_encode(['status' => false, 'response' => ['status' => 'Error', 'msg' => 'Telah terjadi kesalahan, harap ulangi beberapa saat lagi']]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $articleImages = ArticleImage::where('article_id', $article->id)->get();
        foreach ($articleImages as $key => $articleImage) {
            $path = public_path('storage/'.$articleImage->image);
            if (file_exists($path)) {
                unlink($path);
            }

            $image = ArticleImage::findOrFail($articleImage->id);
            $image->delete();
        }

        if (Storage::exists($article->banner)) {
            Storage::delete($article->banner);
        }

        if ($article->delete()) {
            return redirect()->route('admin.article.index')->with(['status' => 'success', 'msg' => 'Informasi berhasil di hapus']);
        }
        return json_encode(['status' => false, 'response' => ['status' => 'Error', 'msg' => 'Telah terjadi kesalahan, harap ulangi beberapa saat lagi']]);
    }
}

app/Http/Controllers/Admin/Article/ImageController.php
<?php

namespace App\Http\Controllers\Admin\Article;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ArticleImage;
use Str;
use File;

class ImageController extends Controller
{

	public function storeImage(Request $request)
	{
		// default name input dropzone is file
		$file 		= $request->file('file');
		$uniq 		= uniqid();
		$name 		= explode('.', $file->getClientOriginalName());
		$ext 		= $name[1];
		$fileName 	= Str::slug($name[0].'-article'.auth()->user()->id.'-'.$uniq).'.'.$name[1];
		$response 	= (object) ['name' => $fileName, 'key' => $uniq, 'option' => 'create', 'id' => $uniq];
		$request->session()->push('admin'.auth()->user()->id.'.article_image', $response);
		$successUpload = $file->storeAs('tmp/article', $fileName);

		if ($successUpload) {
			return response()->json($response, 200);
		} else {
			return response()->json('error', 400);
		}
	}

	public function getImage(Request $request)
	{
		// jika tidak ada request id
		if (isset($request->id)) {
			$id = $request->id;
			$image = [];
			$articleImage = ArticleImage::where('article_id', $id)->get();

			foreach ($articleImage as $key => $data) {
				$fullPath 		= $data->image;
				$fileLocation 	= 'tmp/article/'. $fullPath;
				$getFileName 	= explode('image/article/', $fullPath);
				$getKey 		= explode('-article'.auth()->user()->id.'-', $fullPath);
				$key 			= explode('.', $getKey[1]);
				$image[] = [
					'original' => $fullPath,
					'server' => $fileLocation,
					'size' => File::size(public_path('storage/'.$fullPath)),
					'name' => $fullPath,
					'key' => $key[0]
				];
			}
		} else {
			$image = [];
			// ambil data pada session
			$getImageFromSession = $request->session()->get('admin'.auth()->user()->id.'.article_image');
			if ($getImageFromSession) {
				foreach ($getImageFromSession as $key => $image) {
					$fullPath = $image->name;
					$fileLocation = 'tmp/article/'.$fullPath;
					$getKey = explode('article'.auth()->user()->id.'-', $fullPath);
					$key = explode('.', $getKey[1]);
					$image[] = [
						'original' => $fullPath,
						'server' => $fileLocation,
						'size' => File::size(public_path('storage/'), $fileLocation),
						'name' => $fullPath,
						'key' => $key[0],
					];
				}
			}
		}

		return response()->json(['images' => $image]);
	}

	public function deleteImage(Request $request)
	{
		// ambil file_key
		$fileKey = $request->filekey;
		// ambil data image dari session
		$getImageFromSession = $request->session()->pull('admin'.auth()->user()->id.'.article_image', (object) []);
		// brute force 
		foreach ($getImageFromSession as $key => $data) {
			// ambil data key kemudian samakan dengan nilai file key
			if ($data->key == $fileKey) {
				// file yang akan di hapus
				$deleteFile = $data->name;
				// option sangat di perlukan untuk memastikan method edit atau buat baru
				$option = $data->option;
				$imageId = $data->id;
				// hapus session
				unset($getImageFromSession[$key]);
			}
		}

		$getImageFromSession = $request->session()->put('admin'.auth()->user()->id.'.article_image', array_values($getImageFromSession));
		// cek validasi, jika nilai dari variable option adalah edit
		if ($option == 'edit') {
			$path = public_path('storage/image/article/'. $deleteFile);
			$delete = (object)['delete' => $deleteFile, 'id' => $imageId];
			$request->session()->push('admin'.auth()->user()->id.'.article_image_delete', $delete);
		} else {
			$path = public_path('storage/tmp/article/'.$deleteFile);
			if (file_exists($path)) {
				unlink($path);
			}
		}

		if ($path) {
			return response()->json($deleteFile, 200);
		} else {
			return response()->json('error', 400);
		}
	}
}

resources/views/admin/article/create.blade.php
@extends('layouts.admin')

@section('title')
Buat {{ucwords(str_replace('-',' ',Request::segment(2)))}} baru
@endsection

@section('heading')
<div class="page-header">
	<div class="page-header-content">
		<div class="page-title">
			<h4><span class="text-semibold">{{ucwords(str_replace('-',' ',Request::segment(2)))}}</span> - Buat
                {{ucwords(str_replace('-',' ',Request::segment(2)))}} baru</h4>
		</div>

		<div class="heading-elements">
			{{-- <div class="heading-btn-group"> --}}
				<a href="{{route('admin.article.index')}}" class="btn bg-teal-400 btn-labeled"><b><i class="icon-square-left"></i></b>Kembali</a>
			{{-- </div> --}}
		</div>
	</div>

	<div class="breadcrumb-line breadcrumb-line-component">
		<ul class="breadcrumb">
			<li><a href="{{ route('admin.index') }}"><i class="icon-home2 position-left"></i> Home</a></li>
			<li><a href="{{ route('admin.article.index') }}">{{ucwords(str_replace('-',' ',Request::segment(2)))}}</a></li>
			<li class="active">Buat</li>
		</ul>
	</div>
</div>
@endsection

@section('content')
<form action="{{ route('admin.article.store') }}" method="post" enctype="multipart/form-data" id="formdata">
	@csrf
	<div class="col-lg-12">
		@if ($errors->any())
		@foreach ($errors->all() as $error)
		<label class="label bg-danger">{{ $error }}</label>
		@endforeach
		@endif
		<div class="panel panel-flat panel-body">
			<div class="form-group">
				<label>Nama</label>
				<input type="name" name="name" class="form-control" placeholder="Nama Produk">
			</div>
			<div class="row">
				<div class="col-lg-6">
					<div class="form-group">
						<label>Gambar <b class="text-danger">*</b></label>
						<input type="file" name="banner" class="file-input">
					</div>
				</div>
				<div class="col-lg-6">
					<div class="form-group">
						<label class="control-label">Status <b class="text-danger">*</b></label>
						<div class="checkbox checkbox-switch">
							<label>
								<input type="checkbox" name="status" class="switch">
							</label>
						</div>
					</div>
					<div class="form-group">
						<label>Detail Gambar informasi</label>
						<div class="dropzone" id="imageUpload">
							
						</div>
					</div>
				</div>
			</div>
			<div class="form-group">
				<label>Deskripsi</label>
				<textarea id="editor-full" name="description"></textarea>
			</div>
		</div>
		<button class="btn btn-primary">Simpan</button>
	</div>
</form>
@endsection

@section('min-js')
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/validation/validate.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/selects/bootstrap_multiselect.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/inputs/touchspin.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/selects/select2.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/styling/switch.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/styling/switchery.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/styling/uniform.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/ckeditor/ckeditor.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('admin/js/plugins/notifications/pnotify.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('admin/js/plugins/uploaders/dropzone.min.js') }}"></script>
@endsection

@section('js')
<script type="text/javascript">
	$(document).ready(function(){
		$('#formdata').submit(function(e) {
			e.preventDefault();
			$.ajax({
				url: $(this).attr('action'),
				data: new FormData(this),
				method: 'post',
	            contentType: false,
	            processData: false,
				beforeSend:function(){
					$('body').block({
						message: '<span class="text-semibold"><i class="icon-spinner9 spinner position-left"></i>&nbsp; Data sedang di proses ... </span>',
						overlayCSS: {
							backgroundColor: '#fff',
							opacity: 0.8,
							cursor: 'wait'
						},
						css: {
							border: 0,
							padding: '10px 15px',
							color: '#fff',
							width: 'auto',
							'-webkit-border-radius': 5,
							'-moz-border-radius': 5,
							backgroundColor: '#333'
						}
					});
				}
			}).done(function(e) {
				$('body').unblock();
				var json = $.parseJSON(e);
				// console.log(json.response.url);
		        new PNotify({
		            title: json.response.status,
		            text: json.response.msg,
		            addclass: 'bg-'+json.response.status
		        });
				if (json.status) {
	    			setTimeout(function(){
	    				window.location.href = json.response.url;
	    			},2500);
				} else {
					return;
				}
			}).fail(function(e) {
				$('body').unblock();
				console.log(e);
			})
		});

        $("#description").on('input propertychange', function() {
		    if (this.value.length >= 201) {
                $("#notify").fadeIn();
            } else {
                $("#notify").fadeOut();
                $("#counter").html(this.value.length);
            }
        });
	});

	$(".switch").bootstrapSwitch();
    $(".styled, .multiselect-container input").uniform({
        radioClass: 'choice'
    });
    // File input
    $(".file-styled").uniform({
        wrapperClass: 'bg-blue',
        fileButtonHtml: '<i class="icon-file-plus"></i>'
    });

	$('.select2').select2({
		placeholder: "- Pilih Kategori -",
		minimumResultsForSearch: Infinity
	});

	$(function() {

	    CKEDITOR.replace( 'editor-full', {
	        height: '262px',
	    });
	    
	    CKEDITOR.disableAutoInline = true;

	});

	$(".file-styled").uniform({
	    fileButtonClass: 'action btn bg-pink-400'
	});

	$(".mini-upload").change(function(){
	    var input       = this;
	    var image       = $(this).parents('.media-parent').find('img');
	    var lightbox    = $(this).parents('.media-parent').find('[data-popup="lightbox"]');
	    
	     if (input.files && input.files[0]) {
	        var reader = new FileReader();

	        reader.onload = function (e) {
	            $(lightbox).attr('href', e.target.result);
	            $(image).attr('src', e.target.result);

	        }

	        reader.readAsDataURL(input.files[0]);
	    }
	});

	Dropzone.options.imageUpload = {
		headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}' },
		paramName: 'file',
        dictDefaultMessage: 'Drop files to upload <span>or CLICK</span>',
		url: "{{ route('admin.article.store_image') }}",
		maxFilesize: 12,
		acceptedFiles: ".jpeg,.jpg,.png,.gif",
		addRemoveLinks: true,
		timeout: 5000,
        maxFilesize: 2,
		parallelUploads:1,
		init:function(){
			// Add server images
			var myDropzone = this;
			$.ajax({
				headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}' },
				type: 'GET',
				url: '{{ route('admin.article.get_image') }}',
			}).done(function(data){
				console.log(data);
				let public_path = '{{ url("storage") }}';
				$.each(data.images, function (key, value) {
					var file = {name: value.original, size: value.size};
					myDropzone.options.addedfile.call(myDropzone, file);
					myDropzone.options.thumbnail.call(myDropzone, file, public_path+"/"+value.server);
					let fileuploaded = file.previewElement.querySelector("[data-dz-name]");
					// append the response key to create data-key
					fileuploaded.dataset.key = value.key;
					fileuploaded.innerHTML = value.name;
					myDropzone.emit("complete", file);
				});
			}).error(function(data){
				Swal.fire('Error', 'error getting data, please refresh the page','error');
			});

			this.on("removedfile", function(file, response){
				let dz_name = file.previewElement.querySelector("[data-dz-name]");
				// take the data-key
				let key = dz_name.dataset.key;
				$.ajax({
					headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}' },
					type: 'POST',
					url: '{{ route('admin.article.delete_image') }}',
					data: { filekey: key },
					success: function (data){
                        new PNotify({
                            title: 'success',
                            text: 'File has been successfully removed!!',
                            addclass: 'bg-success'
                        });
					},
					error: function(e) {
                        console.log(e);
                        new PNotify({
                            title: 'error',
                            text: 'File not removed',
                            addclass: 'bg-danger'
                        });
					}
				});
				let fileRef;
				return (fileRef = file.previewElement) != null ?
				fileRef.parentNode.removeChild(file.previewElement) : void 0;
			});
		},
		success: function(file, response)
		{
			let fileuploaded = file.previewElement.querySelector("[data-dz-name]");
			// append the response key to create data-key
			fileuploaded.dataset.key = response.key;
			fileuploaded.innerHTML = response.name;
            new PNotify({
                title: 'success',
                text: 'Upload Success',
                addclass: 'bg-success'
            });
		},
		error: function(file, response)
		{
            let fileRef;
            return (fileRef = file.previewElement) != null ?
            fileRef.parentNode.removeChild(file.previewElement) : void 0;
            new PNotify({
                title: 'error',
                text: 'File not uploaded',
                addclass: 'bg-danger'
            });
		}
    };

	var modalTemplate = '<div class="modal-dialog modal-lg" role="document">\n' +
	    '  <div class="modal-content">\n' +
	    '    <div class="modal-header">\n' +
	    '      <div class="kv-zoom-actions btn-group">{toggleheader}{fullscreen}{borderless}{close}</div>\n' +
	    '      <h6 class="modal-title">{heading} <small><span class="kv-zoom-title"></span></small></h6>\n' +
	    '    </div>\n' +
	    '    <div class="modal-body">\n' +
	    '      <div class="floating-buttons btn-group"></div>\n' +
	    '      <div class="kv-zoom-body file-zoom-content"></div>\n' + '{prev} {next}\n' +
	    '    </div>\n' +
	    '  </div>\n' +
	    '</div>\n';

	// Buttons inside zoom modal
	var previewZoomButtonClasses = {
	    toggleheader: 'btn btn-default btn-icon btn-xs btn-header-toggle',
	    fullscreen: 'btn btn-default btn-icon btn-xs',
	    borderless: 'btn btn-default btn-icon btn-xs',
	    close: 'btn btn-default btn-icon btn-xs'
	};

	// Icons inside zoom modal classes
	var previewZoomButtonIcons = {
	    prev: '<i class="icon-arrow-left32"></i>',
	    next: '<i class="icon-arrow-right32"></i>',
	    toggleheader: '<i class="icon-menu-open"></i>',
	    fullscreen: '<i class="icon-screen-full"></i>',
	    borderless: '<i class="icon-alignment-unalign"></i>',
	    close: '<i class="icon-cross3"></i>'
	};

	// File actions
	var fileActionSettings = {
	    zoomClass: 'btn btn-link btn-xs btn-icon',
	    zoomIcon: '<i class="icon-zoomin3"></i>',
	    dragClass: 'btn btn-link btn-xs btn-icon',
	    dragIcon: '<i class="icon-three-bars"></i>',
	    removeClass: 'btn btn-link btn-icon btn-xs',
	    removeIcon: '<i class="icon-trash"></i>',
	    indicatorNew: '<i class="icon-file-plus text-slate"></i>',
	    indicatorSuccess: '<i class="icon-checkmark3 file-icon-large text-success"></i>',
	    indicatorError: '<i class="icon-cross2 text-danger"></i>',
	    indicatorLoading: '<i class="icon-spinner2 spinner text-muted"></i>'
	};

	var imagePreview 	= [];

	//
	// Basic example
	//

	$('.file-input').fileinput({
	    browseLabel: 'Browse',
	    browseIcon: '<i class="icon-file-plus"></i>',
	    uploadIcon: '<i class="icon-file-upload2"></i>',
	    removeIcon: '<i class="icon-cross3"></i>',
	    layoutTemplates: {
	        icon: '<i class="icon-file-check"></i>',
	        modal: modalTemplate
	    },
	    maxFileCount: 4,
	    maxFileSize: 3000,
	    allowedFileExtensions: ["jpg", "png","jpeg"],
	    initialCaption: "Tidak ada file yang dipilih",
	    initialPreview: imagePreview,
	    previewZoomButtonClasses: previewZoomButtonClasses,
	    previewZoomButtonIcons: previewZoomButtonIcons,
	    fileActionSettings: fileActionSettings
	});
</script>
@endsection