routes/admin.php
<?php

/*
 * Routing khusus admin panel
 */
Route::group(['prefix' => 'administrator', 'middleware' => ['globalvar', 'admin.panel'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('kegiatan-warga/get/images', 'Gallery\GalleryController@getImages')->name('gallery.get.images');
    Route::post('kegiatan-warga/store/images', 'Gallery\GalleryController@storeImages')->name('gallery.store.images');
    Route::post('kegiatan-warga/delete/images', 'Gallery\GalleryController@deleteImages')->name('gallery.delete.images');
    Route::resource('/', 'Dashboard\DashboardController');
    Route::resource('config', 'Config\ConfigController');
    Route::resource('seo', 'Config\SeoController');
    Route::resource('contact', 'Config\ContactController');
    Route::resource('logo', 'Config\LogoController');
    Route::resource('user', 'Config\UserController');
    Route::resource('slider', 'Slider\SliderController');
    Route::resource('kontak', 'ContactUs\ContactUsController')->names([
        'index' => 'contactus.index',
        'create' => 'contactus.create',
        'store' => 'contactus.store',
        'show' => 'contactus.show',
        'edit' => 'contactus.edit',
        'update' => 'contactus.update',
        'destroy' => 'contactus.destroy',
    ])->parameters(['kontak' => 'contactus']);
    Route::resource('produk-warga', 'Merchandise\MerchandiseController')->names([
        'index' => 'merchandise.index',
        'create' => 'merchandise.create',
        'store' => 'merchandise.store',
        'show' => 'merchandise.show',
        'edit' => 'merchandise.edit',
        'update' => 'merchandise.update',
        'destroy' => 'merchandise.destroy',
    ])->parameters(['produk-warga' => 'merchandise']);
    Route::resource('kegiatan-warga', 'Gallery\GalleryController')->names([
        'index' => 'gallery.index',
        'create' => 'gallery.create',
        'store' => 'gallery.store',
        'show' => 'gallery.show',
        'edit' => 'gallery.edit',
        'update' => 'gallery.update',
        'destroy' => 'gallery.destroy',
    ])->parameters(['kegiatan-warga' => 'gallery']);
    Route::resource('berita', 'News\NewsController')->names([
        'index' => 'news.index',
        'create' => 'news.create',
        'store' => 'news.store',
        'show' => 'news.show',
        'edit' => 'news.edit',
        'update' => 'news.update',
        'destroy' => 'news.destroy',
    ])->parameters(['berita' => 'news']);

    Route::resource('informasi', 'Article\ArticleController')->names([
        'index' => 'article.index',
        'create' => 'article.create',
        'store' => 'article.store',
        'show' => 'article.show',
        'edit' => 'article.edit',
        'update' => 'article.update',
        'destroy' => 'article.destroy',
    ])->parameters(['informasi' => 'article']);
    Route::get('informasi/image/get',     'Article\ImageController@getImage')->name('article.get_image');
    Route::post('informasi/image/store',  'Article\ImageController@storeImage')->name('article.store_image');
    Route::post('informasi/image/delete', 'Article\ImageController@deleteImage')->name('article.delete_image');

    Route::get('signout', 'AuthController@signout')->name('signout');
});

Route::group(['prefix' => 'auth', 'namespace' => 'Admin'], function () {
    Route::get('admin', 'AuthController@index')->name('login.admin');
    Route::post('admin', 'AuthController@store')->name('auth.admin');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Frontend', 'as' => 'frontend.', 'middleware' => ['globalvar']], function() {
    Route::get('/', 'Home\HomeController@index')->name('home');
    Route::get('berita', 'News\NewsController@index')->name('news');
    Route::get('berita/{slug}', 'News\NewsController@detail')->name('news.detail');
    Route::get('kegiatan-warga', 'Event\EventController@index')->name('activities');
    Route::get('kegiatan-warga/{slug}', 'Event\EventController@detail')->name('activities.detail');
    Route::get('kontak', 'Contact\ContactController@index')->name('contact');
    Route::get('produk-warga', 'Merchandise\MerchandiseController@index')->name('merchandise');
    Route::get('produk-warga/{slug}', 'Merchandise\MerchandiseController@detail')->name('merchandise.detail');
    Route::get('informasi', 'Information\InformationController@index')->name('informasi');
    Route::get('informasi/{id}', 'Information\InformationController@show')->name('informasi.detail');
    Route::get('cache', function() {
        $artisan = Artisan::call('view:cache');
    	 // $artisan = Artisan::call('migrate');

    	$artisan = Artisan::call('view:clear');
    	echo "Done";
    });
});

app/Models/Gallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Storage;

class Gallery extends Model
{
    protected $fillable = ['name', 'status', 'slug', 'image', 'description'];

    public function showImage()
    {
        if ($this->image != null or Storage::exists($this->image)) {
            return asset('storage/' . $this->image);
        } else {
            return asset('assets/images/default.jpg');
        }
    }

    public function scopeActive($query)
    {
        $query->where('status', 1);
    }

    public function images()
    {
        return $this->hasMany('App\Models\GalleryImage');
    }
}

app/Http/Controllers/Admin/Gallery/GalleryController.php
<?php

namespace App\Http\Controllers\Admin\Gallery;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Gallery;
use App\Models\GalleryImage;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

class GalleryController extends Controller
{
    protected $gallery;
    protected $imageGallery;
    public function __construct()
    {
        $this->gallery = new Gallery;
        $this->imageGallery = new GalleryImage;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $request->session()->forget('admin' . auth()->user()->id . '.gallery.images');
        $request->session()->forget('admin' . auth()->user()->id . '.gallery.delete.images');
        return view('admin.gallery.index', ['models' => Gallery::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['name' => 'required', 'description' => 'required']);

        $create = [
            'name' => $request->name,
            'description' => $request->description,
            'status' => ($request->status) ? true : false,
            'type' => ($request->type) ? 'image' : 'video',
            'slug' => str_slug($request->name),
            'image' => $request->file('image')->store('gallery'),
        ];


        if ($gallery = Gallery::create($create)) {
            // after we save the gallery get the id
            // destination path
            $destinationPath = 'files/gallery/';
            $sourcePath = 'tmp/gallery/';
            // get the gallery image name from sessions
            $imagesFromSession = $request->session()->get('admin' . auth()->user()->id . '.gallery.images');
            if ($imagesFromSession) {
                // let we save the image path to database, and move the image to right destination
                foreach ($imagesFromSession as $key => $image) {
                    // old file path
                    $oldPath = $sourcePath . $image->name;
                    // new file path
                    $newPath = $destinationPath . $image->name;
                    // save the last inserted id
                    $galleryImage = new GalleryImage();
                    $galleryImage->gallery_id = $gallery->id;
                    // save new path for the gallery image
                    $galleryImage->image = $newPath;
                    $galleryImage->save();
                    // move old file to new file
                    Storage::move($oldPath, $newPath);
                }
            }
            return json_encode(['status' => true, 'response' => ['status' => 'success', 'msg' => 'Data gallery berhasil di tambahkan', 'url' => route('admin.gallery.index')]]);
        }
        return json_encode(['status' => false, 'response' => ['status' => 'error', 'msg' => 'Terjadi kesalahan, ulangi beberapa saat lagi']]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $gallery
     * @return \Illuminate\Http\Response
     */
    public function show($gallery)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $gallery
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$gallery)
    {
        $request->session()->forget('admin' . auth()->user()->id . '.gallery.images');
        $request->session()->forget('admin' . auth()->user()->id . '.gallery.delete.images');
        // take the image
        $galleryImage = GalleryImage::whereGalleryId($gallery)->get();
        // let's build the sessions
        foreach ($galleryImage as $key => $image) {
            $path = $image->image;
            // take the key
            $key = explode('KGTNWRG' . auth()->user()->id . '-', $path);
            // the filename
            $file = explode('files/gallery/', $path);
            $sessionsImage = (object) ['name' => $file[1], 'key' => $key[1], 'option' => 'edit', 'id' => $image->id];
            $request->session()->push('admin' . auth()->user()->id . '.gallery.images', $sessionsImage);
        }
        $galleries = Gallery::findOrFail($gallery);
        return view('admin.gallery.edit', compact('galleries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $gallery
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $gallery)
    {
        $request->validate(['name' => 'required', 'description' => 'required']);
        $galleries = Gallery::findOrFail($gallery);

        if ($request->hasFile('image')) {

            if (Storage::exists($galleries->image)) {
                Storage::delete($galleries->image);
            }

            $fields = [
                'name' => $request->name,
                'description' => $request->description,
                'status' => ($request->status) ? true : false,
                'type' => ($request->type) ? 'image' : 'video',
                'slug' => str_slug($request->name),
                'image' => $request->file('image')->store('gallery'),
            ];

            $update = $galleries->update($fields);
        } else {
            $fields = [
                'name' => $request->name,
                'description' => $request->description,
                'status' => ($request->status) ? true : false,
                'type' => ($request->type) ? 'image' : 'video',
                'slug' => str_slug($request->name),
            ];

            $update = $galleries->update($fields);
        }

        if ($update) {
            // destination path

            $destinationPath = 'files/gallery/';
            $sourcePath = 'tmp/gallery/';
            // get the gallery image name from sessions
            $imagesFromSession = $request->session()->get('admin' . auth()->user()->id . '.gallery.images');
            if ($imagesFromSession) {
                // let we save the image path to database, and move the image to right destination
                foreach ($imagesFromSession as $key => $image) {
                    // only process if the option is create
                    if ($image->option == 'create') {
                        // old file path
                        $oldPath = $sourcePath . $image->name;
                        // new file path
                        $newPath = $destinationPath . $image->name;
                        // save the last inserted id
                        $galleryImage = new GalleryImage();
                        $galleryImage->gallery_id = $galleries->id;
                        // save new path for the gallery image
                        $galleryImage->image = $newPath;
                        $galleryImage->save();
                        // move old file to new file
                        Storage::move($oldPath, $newPath);
                    }
                }
            }

            // now we process the deletion image from sessions we have, it will remove the record from database too
            $imagesDeleteSession = $request->session()->get('admin' . auth()->user()->id . '.gallery.delete.images');
            if ($imagesDeleteSession) {
                // let we save the image path to database, and move the image to right destination
                foreach ($imagesDeleteSession as $key => $image) {
                    // delete the images
                    $path = public_path('storage/files/gallery/' . $image->delete);
                    if (file_exists($path)) {
                        unlink($path);
                    }
                    // delete from database too
                    $galleryImage = GalleryImage::findOrFail($image->id);
                    $galleryImage->delete();
                }
            }
            return json_encode([
                'status' => true,
                'response' => [
                    'status' => 'success',
                    'msg' => 'Kegiatan warga berhasil di perbarui',
                    'url' => route('admin.gallery.index')
                ]
            ]);
        }
        return json_encode([
            'status' => false,
            'response' => ['status' => 'error', 'msg' => 'Terjadi kesalahan, harap ulangi beberapa saat lagi']
        ]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $gallery
     * @return \Illuminate\Http\Response
     */
    public function destroy($gallery)
    {
        $decrypted = $gallery;
        $gallery = Gallery::findOrFail($decrypted);
        $galleryImage = GalleryImage::whereGalleryId($gallery->id)->get();
        foreach ($galleryImage as $key => $image) {
            // delete the images
            $path = public_path('storage/' . $image->image);
            if (file_exists($path)) {
                unlink($path);
            }
            $galleryImageDelete = GalleryImage::findOrFail($image->id);
            $galleryImageDelete->delete();
        }

        if ($gallery->delete()) {
            return redirect()->route('admin.gallery.index')->with(['status' => 'success', 'msg' => 'Kegiatan warga berhasil di hapus']);
        }
        return redirect()->route('admin.gallery.index')->with(['status' => 'danger', 'msg' => 'Terjadi kesalahan, harap ulangi beberapa saat lagi']);
    }

    /**
     * Store only gallery images that uploaded by admin
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */

resources/views/admin/gallery/create.blade.php
@extends('layouts.admin')

@section('title')
Buat gallery baru
@endsection

@section('heading')
<div class="page-header">
	<div class="page-header-content">
		<div class="page-title">
			<h4><span class="text-semibold">{{ucwords(str_replace('-',' ',Request::segment(2)))}}</span> - Buat
                {{ucwords(str_replace('-',' ',Request::segment(2)))}} baru</h4>
		</div>

		<div class="heading-elements">
			{{-- <div class="heading-btn-group"> --}}
				<a href="{{route('admin.gallery.index')}}" class="btn bg-teal-400 btn-labeled"><b><i class="icon-square-left"></i></b>Kembali</a>
			{{-- </div> --}}
		</div>
	</div>

	<div class="breadcrumb-line breadcrumb-line-component">
		<ul class="breadcrumb">
			<li><a href="{{ route('admin.index') }}"><i class="icon-home2 position-left"></i> Home</a></li>
			<li><a href="{{ route('admin.gallery.index') }}">{{ucwords(str_replace('-',' ',Request::segment(2)))}}</a></li>
			<li class="active">Buat</li>
		</ul>
	</div>
</div>
@endsection

@section('content')
<form class="form-horizontal" method="post" action="{{ route('admin.gallery.store') }}" id="formdata" enctype="multipart/form-data">
	@csrf
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<div class="panel panel-flat" style="min-height: 340px">
				<div class="panel-body">
					<div class="col-md-12">
                        <div id="image">
                            <div class="form-group">
                                <label>Masukkan Gambar sebagai banner</label>
                                <input type="file" id="fileImage" name="image" class="file-input" accept="image/*" data-show-upload="false">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Status <b class="text-danger">*</b></label><br>
                            <input type="checkbox" name="status" class="switch" data-on-text='Aktif' data-off-text='Non-Aktif'>
                        </div>
						<div class="form-group">
							<label>Nama <b class="text-danger">*</b></label>
							<input type="text" name="name" class="form-control" placeholder="John Doe">
						</div>
						<div class="form-group">
							<label>Description <b class="text-danger">*</b></label>
							<textarea class="form-control" name="description" id="description" rows="6" placeholder="Deskripsi galleri max 200 karakter" maxlength="201"></textarea>
							<span id="notify" class="text-danger" style="display: none">Batas karakter sudah mencapai 200</span>
							<span id='counter' class="pull-right text-justify"></span>
						</div>
						<div class="col-sm-12 col-md-12">
							<label>Dokumentasi Kegiatan Warga</label>
							<div class="dropzone" id="frmFileUpload">

							</div>
						</div>
					</div>
				</div>
			</div>
			<button type="submit" class="btn btn-primary pull-right">Buat Gallery<i class="icon-arrow-right14 position-right"></i></button>
		</div>
	</div>
</form>
@endsection

@section('min-js')
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/validation/validate.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/selects/bootstrap_multiselect.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/inputs/touchspin.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/selects/select2.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/styling/switch.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/styling/switchery.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/styling/uniform.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/ckeditor/ckeditor.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('admin/js/plugins/notifications/pnotify.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('admin/js/plugins/uploaders/dropzone.min.js') }}"></script>
@endsection

@section('js')
    <script type="text/javascript" src="{{asset('admin/js/pages/form_validation.js')}}"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			$('#formdata').submit(function(e) {
				e.preventDefault();
				$.ajax({
					url: $(this).attr('action'),
					data: new FormData(this),
					method: 'post',
		            contentType: false,
		            processData: false,
					beforeSend:function(){
						$('body').block({
							message: '<span class="text-semibold"><i class="icon-spinner9 spinner position-left"></i>&nbsp; Data sedang di proses ... </span>',
							overlayCSS: {
								backgroundColor: '#fff',
								opacity: 0.8,
								cursor: 'wait'
							},
							css: {
								border: 0,
								padding: '10px 15px',
								color: '#fff',
								width: 'auto',
								'-webkit-border-radius': 5,
								'-moz-border-radius': 5,
								backgroundColor: '#333'
							}
						});
					}
				}).done(function(e) {
					$('body').unblock();
					var json = $.parseJSON(e);
					// console.log(json.response.url);
			        new PNotify({
			            title: json.response.status,
			            text: json.response.msg,
			            addclass: 'bg-'+json.response.status
			        });
					if (json.status) {
		    			setTimeout(function(){
		    				window.location.href = json.response.url;
		    			},2500);
					} else {
						return;
					}
				}).fail(function(e) {
					$('body').unblock();
					console.log(e);
				})
			});

            $("#description").on('input propertychange', function() {
			    if (this.value.length >= 201) {
                    $("#notify").fadeIn();
                } else {
                    $("#notify").fadeOut();
                    $("#counter").html(this.value.length);
                }
            });
		});

		Dropzone.options.frmFileUpload = {
			headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') },
			paramName: 'file',
            dictDefaultMessage: 'Drop files to upload <span>or CLICK</span>',
			url: "{{ route('admin.gallery.store.images') }}",
			maxFilesize: 12,
			acceptedFiles: ".jpeg,.jpg,.png,.gif",
			addRemoveLinks: true,
			timeout: 5000,
            maxFilesize: 2,
			parallelUploads:1,
			init:function(){
				// Add server images
				var myDropzone = this;
				$.ajax({
					headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') },
					type: 'GET',
					url: '{{ route("admin.gallery.get.images") }}',
				}).done(function(data){
					console.log(data);
					let public_path = '{{ url("storage") }}';
					$.each(data.images, function (key, value) {
						var file = {name: value.original, size: value.size};
						myDropzone.options.addedfile.call(myDropzone, file);
						myDropzone.options.thumbnail.call(myDropzone, file, public_path+"/"+value.server);
						let fileuploaded = file.previewElement.querySelector("[data-dz-name]");
						// append the response key to create data-key
						fileuploaded.dataset.key = value.key;
						fileuploaded.innerHTML = value.name;
						myDropzone.emit("complete", file);
					});
				}).error(function(data){
					Swal.fire('Error', 'error getting data, please refresh the page','error');
				});

				this.on("removedfile", function(file, response){
					let dz_name = file.previewElement.querySelector("[data-dz-name]");
					// take the data-key
					let key = dz_name.dataset.key;
					$.ajax({
						headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') },
						type: 'POST',
						url: '{{ route("admin.gallery.delete.images") }}',
						data: { filekey: key },
						success: function (data){
                            new PNotify({
                                title: 'success',
                                text: 'File has been successfully removed!!',
                                addclass: 'bg-success'
                            });
						},
						error: function(e) {
                            console.log(e);
                            new PNotify({
                                title: 'error',
                                text: 'File not removed',
                                addclass: 'bg-danger'
                            });
						}
					});
					let fileRef;
					return (fileRef = file.previewElement) != null ?
					fileRef.parentNode.removeChild(file.previewElement) : void 0;
				});
			},
			success: function(file, response)
			{
				let fileuploaded = file.previewElement.querySelector("[data-dz-name]");
				// append the response key to create data-key
				fileuploaded.dataset.key = response.key;
				fileuploaded.innerHTML = response.name;
                new PNotify({
                    title: 'success',
                    text: 'Upload Success',
                    addclass: 'bg-success'
                });
			},
			error: function(file, response)
			{
                let fileRef;
                return (fileRef = file.previewElement) != null ?
                fileRef.parentNode.removeChild(file.previewElement) : void 0;
                new PNotify({
                    title: 'error',
                    text: 'File not uploaded',
                    addclass: 'bg-danger'
                });
			}
        };

        var modalTemplate = '<div class="modal-dialog modal-lg" role="document">\n' +
            '  <div class="modal-content">\n' +
            '    <div class="modal-header">\n' +
            '      <div class="kv-zoom-actions btn-group">{toggleheader}{fullscreen}{borderless}{close}</div>\n' +
            '      <h6 class="modal-title">{heading} <small><span class="kv-zoom-title"></span></small></h6>\n' +
            '    </div>\n' +
            '    <div class="modal-body">\n' +
            '      <div class="floating-buttons btn-group"></div>\n' +
            '      <div class="kv-zoom-body file-zoom-content"></div>\n' + '{prev} {next}\n' +
            '    </div>\n' +
            '  </div>\n' +
            '</div>\n';

        var previewZoomButtonClasses = {
            toggleheader: 'btn btn-default btn-icon btn-xs btn-header-toggle',
            fullscreen: 'btn btn-default btn-icon btn-xs',
            borderless: 'btn btn-default btn-icon btn-xs',
            close: 'btn btn-default btn-icon btn-xs'
        };

        var previewZoomButtonIcons = {
            prev: '<i class="icon-arrow-left32"></i>',
            next: '<i class="icon-arrow-right32"></i>',
            toggleheader: '<i class="icon-menu-open"></i>',
            fullscreen: '<i class="icon-screen-full"></i>',
            borderless: '<i class="icon-alignment-unalign"></i>',
            close: '<i class="icon-cross3"></i>'
        };

        var fileActionSettings = {
            zoomClass: 'btn btn-link btn-xs btn-icon',
            zoomIcon: '<i class="icon-zoomin3"></i>',
            dragClass: 'btn btn-link btn-xs btn-icon',
            dragIcon: '<i class="icon-three-bars"></i>',
            removeClass: 'btn btn-link btn-icon btn-xs',
            removeIcon: '<i class="icon-trash"></i>',
            indicatorNew: '',
            indicatorSuccess: '<i class="icon-checkmark3 file-icon-large text-success"></i>',
            indicatorError: '<i class="icon-cross2 text-danger"></i>',
            indicatorLoading: '<i class="icon-spinner2 spinner text-muted"></i>'
        };

        $('.file-input').fileinput({
            browseLabel: 'Browse',
            browseIcon: '<i class="icon-file-plus"></i>',
            layoutTemplates: {
                icon: '<i class="icon-file-check"></i>',
                modal: modalTemplate
            },
            initialCaption: "No file selected",
            previewZoomButtonClasses: previewZoomButtonClasses,
            previewZoomButtonIcons: previewZoomButtonIcons,
            fileActionSettings: fileActionSettings
        });
	</script>
@endsection

resources/views/admin/gallery/index.blade.php
@extends('layouts.admin')

@section('title')
Semua data {{str_replace('-',' ',Request::segment(2))}}
@endsection

@section('heading')
<div class="page-header">
	<div class="page-header-content">
		<div class="page-title">
			<h4><span class="text-semibold">{{ucwords(str_replace('-',' ',Request::segment(2)))}}</span> - Semua data {{str_replace('-',' ',Request::segment(2))}}</h4>
		</div>

		<div class="heading-elements">
			{{-- <div class="heading-btn-group"> --}}
				<a href="{{route('admin.gallery.create')}}" class="btn bg-teal-400 btn-labeled"><b><i class="icon-googleplus5"></i></b>Tambahkan {{str_replace('-',' ',Request::segment(2))}}</a>
			{{-- </div> --}}
		</div>
	</div>

	<div class="breadcrumb-line breadcrumb-line-component">
		<ul class="breadcrumb">
			<li><a href="{{ route('admin.index') }}"><i class="icon-home2 position-left"></i> Home</a></li>
			<li class="active">{{ucwords(str_replace('-',' ',Request::segment(2)))}}</li>
		</ul>
	</div>
</div>
@endsection

@section('content')
	<div class="panel panel-flat">

		<table class="table datatable-basic {{-- table-bordered --}} gallery-table">
			<thead>
				<tr class="bg-slate">
					<th>No</th>
					<th>Image Preview</th>
					<th>Deskripsi</th>
					<th>Status</th>
					<th class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
				{{-- @dump($models) --}}
				@foreach($models as $key => $model)
				<tr>
					<td>{{ $key+1 }}</td>
					<td width="200">
						<img class="img-thumbnail" src="{{$model->showImage()}}" alt="" style="width: 100%">
					</td>
					<td>
						<span>{{ str_limit($model->description, '150') }}</span>
					</td>
					<td>
						<label class="label {{ ($model->status == 1) ? 'bg-primary' : 'bg-danger' }}">{{ ($model->status == 1) ? 'Active' : 'Non Active' }}</label>
					</td>
					<td class="text-center">
						<ul class="icons-list">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<i class="icon-menu9"></i>
								</a>

								<ul class="dropdown-menu dropdown-menu-right">
									<li><a href="{{ route('admin.gallery.edit', $model->id) }}"><i class="icon-pencil"></i> Edit</a></li>
									<li><a class="delete-modal" href="{{route('admin.gallery.destroy', $model->id)}}"><i class="icon-trash"></i> Hapus</a></li>
								</ul>
							</li>
						</ul>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
    </div>
    <form id="form-delete" method="post" hidden>
        {{csrf_field()}} {{method_field('DELETE')}}
    </form>
@endsection

@section('min-js')
	<script type="text/javascript" src="{{ asset('admin/js/plugins/tables/datatables/datatables.min.js')}}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/selects/select2.min.js')}}"></script>
@endsection
@section('js')
    <script type="text/javascript" src="{{ asset('admin/js/pages/datatables_basic.js')}}"></script>
    <script type="text/javascript">
        $(".gallery-table").on('click', '.delete-modal', function (e) {
            e.preventDefault();
            let href = $(this).attr('href');
            $('#form-delete').attr('action', href);
            $('#form-delete').submit();
        });
    </script>
@endsection