routes/admin.php
<?php

/*
 * Routing khusus admin panel
 */
Route::group(['prefix' => 'administrator', 'middleware' => ['globalvar', 'admin.panel'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('kegiatan-warga/get/images', 'Gallery\GalleryController@getImages')->name('gallery.get.images');
    Route::post('kegiatan-warga/store/images', 'Gallery\GalleryController@storeImages')->name('gallery.store.images');
    Route::post('kegiatan-warga/delete/images', 'Gallery\GalleryController@deleteImages')->name('gallery.delete.images');
    Route::resource('/', 'Dashboard\DashboardController');
    Route::resource('config', 'Config\ConfigController');
    Route::resource('seo', 'Config\SeoController');
    Route::resource('contact', 'Config\ContactController');
    Route::resource('logo', 'Config\LogoController');
    Route::resource('user', 'Config\UserController');
    Route::resource('slider', 'Slider\SliderController');
    Route::resource('kontak', 'ContactUs\ContactUsController')->names([
        'index' => 'contactus.index',
        'create' => 'contactus.create',
        'store' => 'contactus.store',
        'show' => 'contactus.show',
        'edit' => 'contactus.edit',
        'update' => 'contactus.update',
        'destroy' => 'contactus.destroy',
    ])->parameters(['kontak' => 'contactus']);
    Route::resource('produk-warga', 'Merchandise\MerchandiseController')->names([
        'index' => 'merchandise.index',
        'create' => 'merchandise.create',
        'store' => 'merchandise.store',
        'show' => 'merchandise.show',
        'edit' => 'merchandise.edit',
        'update' => 'merchandise.update',
        'destroy' => 'merchandise.destroy',
    ])->parameters(['produk-warga' => 'merchandise']);
    Route::resource('kegiatan-warga', 'Gallery\GalleryController')->names([
        'index' => 'gallery.index',
        'create' => 'gallery.create',
        'store' => 'gallery.store',
        'show' => 'gallery.show',
        'edit' => 'gallery.edit',
        'update' => 'gallery.update',
        'destroy' => 'gallery.destroy',
    ])->parameters(['kegiatan-warga' => 'gallery']);
    Route::resource('berita', 'News\NewsController')->names([
        'index' => 'news.index',
        'create' => 'news.create',
        'store' => 'news.store',
        'show' => 'news.show',
        'edit' => 'news.edit',
        'update' => 'news.update',
        'destroy' => 'news.destroy',
    ])->parameters(['berita' => 'news']);

    Route::resource('informasi', 'Article\ArticleController')->names([
        'index' => 'article.index',
        'create' => 'article.create',
        'store' => 'article.store',
        'show' => 'article.show',
        'edit' => 'article.edit',
        'update' => 'article.update',
        'destroy' => 'article.destroy',
    ])->parameters(['informasi' => 'article']);
    Route::get('informasi/image/get',     'Article\ImageController@getImage')->name('article.get_image');
    Route::post('informasi/image/store',  'Article\ImageController@storeImage')->name('article.store_image');
    Route::post('informasi/image/delete', 'Article\ImageController@deleteImage')->name('article.delete_image');

    Route::get('signout', 'AuthController@signout')->name('signout');
});

Route::group(['prefix' => 'auth', 'namespace' => 'Admin'], function () {
    Route::get('admin', 'AuthController@index')->name('login.admin');
    Route::post('admin', 'AuthController@store')->name('auth.admin');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Frontend', 'as' => 'frontend.', 'middleware' => ['globalvar']], function() {
    Route::get('/', 'Home\HomeController@index')->name('home');
    Route::get('berita', 'News\NewsController@index')->name('news');
    Route::get('berita/{slug}', 'News\NewsController@detail')->name('news.detail');
    Route::get('kegiatan-warga', 'Event\EventController@index')->name('activities');
    Route::get('kegiatan-warga/{slug}', 'Event\EventController@detail')->name('activities.detail');
    Route::get('kontak', 'Contact\ContactController@index')->name('contact');
    Route::get('produk-warga', 'Merchandise\MerchandiseController@index')->name('merchandise');
    Route::get('produk-warga/{slug}', 'Merchandise\MerchandiseController@detail')->name('merchandise.detail');
    Route::get('informasi', 'Information\InformationController@index')->name('informasi');
    Route::get('informasi/{id}', 'Information\InformationController@show')->name('informasi.detail');
    Route::get('cache', function() {
        $artisan = Artisan::call('view:cache');
    	 // $artisan = Artisan::call('migrate');

    	$artisan = Artisan::call('view:clear');
    	echo "Done";
    });
});

app/Models/Config.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Storage;

class Config extends Model
{
    protected $fillable = ['name', 'logo', 'logo_white', 'icon', 'phone', 'email', 'fax', 'address', 'description', 'gmap_loc', 'koordinate'];

    public function getLatitude()
    {
    	$data = explode("|", $this->koordinate);
    	return $data[0];
    }

    public function getLongtitude()
    {
    	$data = explode('|', $this->koordinate);
    	return $data[1];
    }

    public function showLogo()
    {
        if ($this->logo != null or Storage::exists($this->logo)) {
            return asset('storage/' . $this->logo);
        } else {
            return asset('assets/images/default-logo.png');
        }
    }

    public function showIcon()
    {
        if ($this->icon != null or Storage::exists($this->icon)) {
            return asset('storage/' . $this->icon);
        } else {
            return asset('assets/images/default-icon.png');
        }
    }
}

app/Http/Controllers/Admin/Config/ConfigController.php
<?php

namespace App\Http\Controllers\Admin\Config;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Config;

class ConfigController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Config $config)
    {
        return view('admin.config.website', ['config' => $config]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Config $config)
    {
        $request->validate([
            'name' => 'required',
            'address' => 'required',
            'gmap_loc' => 'required',
            'description' => 'required',
            'koordinate' => 'required',
        ]);

        if ($config->update($request->only('name', 'address', 'gmap_loc', 'description', 'koordinate'))) {

            // return redirect()->route('admin.config.edit', $config->id);
            return json_encode(['status' => true, 'response' => ['status' => 'success', 'msg' => 'Tentang website berhasil di perbarui', 'url' => route('admin.config.edit', $config->id)]]);
        }

        return json_encode(['status' => false, 'response' => ['status' => 'error', 'msg' => 'Terjadi kesalahan, harap ulangi beberapa saat lagi']]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/Config/ContactController.php
<?php

namespace App\Http\Controllers\Admin\Config;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Config as Contact;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.config.contact');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        return view('admin.config.contact', ['contact' => $contact]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contact $contact)
    {
        $request->validate(['email' => 'required', 'phone' => 'required']);

        if ($contact->update($request->all())) {
            // return redirect()->route('admin.contact.edit', $contact->id);
            return json_encode(['status' => true, 'response' => ['status' => 'success', 'msg' => 'Kontak website berhasil di perbarui', 'url' => route('admin.contact.edit', $contact->id)]]);
        }
        return json_encode(['status' => false, 'response' => ['status' => 'error', 'msg' => 'Terjadi kesalahan, harap ulangi beberapa saat lagi']]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/Config/LogoController.php
<?php

namespace App\Http\Controllers\Admin\Config;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Config as Logo;
use Storage;

class LogoController extends Controller
{
    protected $logo;
    public function __construct()
    {
        $this->logo = new Logo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.config.logo');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Logo $logo)
    {
        return view('admin.config.logo', ['logo' => $logo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Logo $logo)
    {
        $request->validate(['logo' => 'image', 'logo_white' => 'image', 'icon' => 'image']);
        /*
         * KODINGAN INI BERISI BAD LOGIC
        */
        if ($request->hasFile('logo')) {
           if (Storage::exists($logo->logo)) {
                Storage::delete($logo->logo);
            }

            $field = [
                'logo' => $request->file('logo')->store('logo')
            ];
            $update = $logo->update($field);

        } elseif ($request->hasFile('logo_white')) {
            if (Storage::exists($logo->logo_white)) {
                Storage::delete($logo->logo_white);
            }

            $field = [
                'logo_white' => $request->file('logo_white')->store('logo')
            ];
            $update = $logo->update($field);
        
        } elseif ($request->hasFile('icon')) {
            if (Storage::exists($logo->icon)) {
                Storage::delete($logo->icon);
            }

            $field = [
                'icon' => $request->file('icon')->store('logo')
            ];
            $update = $logo->update($field);
        } else {
            Storage::delete($logo->logo);
            Storage::delete($logo->logo_white);
            Storage::delete($logo->icon);

            $field = [
                'logo' => $request->file('logo')->store('logo'),
                'logo_white' => $request->file('logo_white')->store('logo'),
                'icon' => $request->file('icon')->store('logo')
            ];

            $update = $logo->update($field);
        }

        if ($update) {
            return json_encode(['status' => true, 'response' => ['status' => 'success', 'msg' => 'Tentang website berhasil di perbarui', 'url' => route('admin.logo.edit', $logo->id)]]);
        }
        return json_encode(['status' => false, 'response' => ['status' => 'error', 'msg' => 'Terjadi kesalahan, harap ulangi beberapa saat lagi']]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/Config/SeoController.php
<?php

namespace App\Http\Controllers\Admin\Config;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Seo;

class SeoController extends Controller
{
    protected $seo;
    public function __construct()
    {
        $this->seo = new Seo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.config.seo');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Seo $seo)
    {
        return view('admin.config.seo', ['seo' => $seo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Seo $seo)
    {
        $request->validate([
            'title' => 'required',
            'author' => 'required',
            'keyword' => 'required',
            'tagline' => 'required',
        ]);

        if ($seo->update($request->all())) {
            return json_encode(['status' => true, 'response' => ['status' => 'success', 'msg' => 'Seo website berhasil di perbarui', 'url' => route('admin.seo.edit', $seo->id)]]);
        }
        return json_encode(['status' => false, 'response' => ['status' => 'error', 'msg' => 'Terjadi kesalahan, harap ulangi beberapa saat lagi']]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/config/contact.blade.php
@extends('layouts.admin')

@section('title')
Pengaturan contact website
@endsection

@section('heading')
<div class="page-header">
	<div class="page-header-content">
		<div class="page-title">
			<h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Pengaturan</span> - Kontak website</h4>
		</div>
	</div>

	<div class="breadcrumb-line breadcrumb-line-component">
		<ul class="breadcrumb">
			<li><a href="{{ route('admin.index') }}"><i class="icon-home2 position-left"></i> Home</a></li>
			<li><a href="#">Pengaturan</a></li>
			<li class="active">kontak</li>
		</ul>
	</div>
</div>
@endsection

@section('content')
<h6 class="content-group text-semibold">
	<span class="text-primary"><i class="icon-magazine"></i> Pengaturan</span> Kontak Website
	<small class="display-block">Mengatur kontak website anda</small>
</h6>
<div class="row">
	<div class="col-lg-12">
		<div class="table tab-content-bordered">
			@include('admin.config.nav')
			<div class="tab-content">
				<div class="tab-pane active">
					<div style="padding: 20px">
						<form id="contact" method="post" action="{{ route('admin.contact.update', $config->id) }}" class="form-horizontal">
							@csrf
							@method('PUT')
							<div class="form-group">
								<label class="control-label col-md-2">Email <b class="text-danger">*</b></label>
								<div class="col-md-10">
									<input type="email" name="email" class="form-control" placeholder="Email anda" value="{{ $contact->email }}">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-2">Phone <b class="text-danger">*</b></label>
								<div class="col-md-10">
									<input type="text" name="phone" class="form-control" placeholder="No Tephone anda" value="{{ $contact->phone }}">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-2">Fax <b class="text-danger">*</b><span>( Opsional )</span></label>
								<div class="col-md-10">
									<input type="text" name="fax" class="form-control" placeholder="Fax. ex:031193XXX" value="{{ $contact->fax }}">
								</div>
							</div>
							<div class="form-group">
								<div class="col-md-12">
									<button type="submit" class="btn btn-primary pull-right">Perbarui</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('js')
<script type="text/javascript">
	$("#contact").submit(function(e) {
		e.preventDefault();
		$.ajax({
			url: $("#contact").attr('action'),
			method: 'post',
			data: new FormData($("#contact")[0]),
			processData: false,
			contentType: false,
			beforeSend:function() {
				$('body').block({
					message: '<span class="text-semibold"><i class="icon-spinner9 spinner position-left"></i>&nbsp; Sedang memperbarui data ... </span>',
					overlayCSS: {
						backgroundColor: '#fff',
						opacity: 0.8,
						cursor: 'wait'
					},
					css: {
						border: 0,
						padding: '10px 15px',
						color: '#fff',
						width: 'auto',
						'-webkit-border-radius': 5,
						'-moz-border-radius': 5,
						backgroundColor: '#333'
					}
				});
			}
		}).done(function(data) {
			$('body').unblock();
			// console.log(data);
			var json = $.parseJSON(data);

			Swal.fire({
			  // position: 'center',
			  // width: 600,
			  type: ''+json.response.status+'',
			  title: json.response.status,
			  text: json.response.msg,
			  showConfirmButton: false,
			  timer: 2000
			});

			if (json.status) {
				setTimeout(function(){
					window.location.href = json.response.url;
				},2500);
			} else {
				return;
			}
		}).fail(function(data) {
			$('body').unblock();
			console.log(data);
		})
	});
</script>
@endsection

resources/views/admin/config/logo.blade.php
@extends('layouts.admin')

@section('title')
Pengaturan logo website
@endsection

@section('heading')
<div class="page-header">
	<div class="page-header-content">
		<div class="page-title">
			<h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Pengaturan</span> - logo website</h4>
		</div>
	</div>

	<div class="breadcrumb-line breadcrumb-line-component">
		<ul class="breadcrumb">
			<li><a href="{{ route('admin.index') }}"><i class="icon-home2 position-left"></i> Home</a></li>
			<li><a href="#">Pengaturan</a></li>
			<li class="active">logo</li>
		</ul>
	</div>
</div>
@endsection

@section('content')
<h6 class="content-group text-semibold">
	<span class="text-primary"><i class="icon-magazine"></i> Pengaturan</span> Logo Website
	<small class="display-block">Mengatur logo website anda</small>
</h6>

<div class="row">
	<div class="col-lg-12">
		<div class="table tab-content-bordered">
			@include('admin.config.nav')
			<div class="tab-content">
				<div class="tab-pane active">
					<div style="padding: 20px">
						<form id="logo" class="form-horizontal" action="{{ route('admin.logo.update', $config->id) }}" method="post" enctype="multipart/form-data">
							@csrf
							@method('PUT')
							<div class="form-group">
								<label class="control-label col-md-2">Logo <b class="text-danger">*</b></label>
								<div class="col-md-10">
									<input type="file" class="file-input-custom" name="logo">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-2">Icon <b class="text-danger">*</b></label>
								<div class="col-md-10">
									<input type="file" name="icon" class="file-input-custom">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-2">Logo White <b class="text-danger">*</b></label>
								<div class="col-md-10">
									<input type="file" name="logo_white" class="file-input-custom">
								</div>
							</div>
							<div class="form-group">
								<button class="btn btn-info">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('min-js')
<script type="text/javascript" src="{{ asset('admin/js/plugins/uploaders/fileinput.min.js') }}"></script>
@endsection

@section('js')
{{-- <script type="text/javascript" src="{{ asset('admin/js/pages/uploader_bootstrap.js') }}"></script> --}}
<script type="text/javascript">

$("#logo").submit(function(e) {
	e.preventDefault();
	var form = new FormData($("config")[0]);
	$.ajax({
		url: $("#logo").attr('action'),
		method: 'post',
		data: new FormData($("#logo")[0]),
		processData: false,
		contentType: false,
		beforeSend:function() {
			$('body').block({
				message: '<span class="text-semibold"><i class="icon-spinner9 spinner position-left"></i>&nbsp; Sedang memperbarui data ... </span>',
				overlayCSS: {
					backgroundColor: '#fff',
					opacity: 0.8,
					cursor: 'wait'
				},
				css: {
					border: 0,
					padding: '10px 15px',
					color: '#fff',
					width: 'auto',
					'-webkit-border-radius': 5,
					'-moz-border-radius': 5,
					backgroundColor: '#333'
				}
			});
		}
	}).done(function(data) {
		$('body').unblock();
		// console.log(data);
		var json = $.parseJSON(data);

		Swal.fire({
		  // position: 'center',
		  // width: 600,
		  type: ''+json.response.status+'',
		  title: json.response.status,
		  text: json.response.msg,
		  showConfirmButton: false,
		  timer: 2000
		});

		if (json.status) {
			setTimeout(function(){
				window.location.href = json.response.url;
			},2500);
		} else {
			return;
		}
	}).fail(function(data) {
		$('body').unblock();
		console.log(data);
	})
});
	$("input[name=logo]").fileinput({
    	previewFileType: 'image',
        browseLabel: 'Select',
        browseClass: 'btn bg-slate-700',
        browseIcon: '<i class="icon-image2 position-left"></i> ',
        removeLabel: 'Remove',
        removeClass: 'btn btn-danger',
        removeIcon: '<i class="icon-cancel-square position-left"></i> ',
        uploadClass: 'hidden',
        uploadIcon: '<i class="icon-file-upload position-left"></i> ',
        layoutTemplates: {
            // caption: '<div tabindex="-1" class="form-control file-caption {class}">\n' + '<span class="icon-file-plus kv-caption-icon"></span><div class="file-caption-name"></div>\n' + '</div>'
        },
        initialPreview: ["<img src='{{ asset('storage/'.$logo->logo) }}' class='file-preview-image' alt=''>",],
        overwriteInitial: true,
	});

	$("input[name=icon]").fileinput({
    	previewFileType: 'image',
        browseLabel: 'Select',
        browseClass: 'btn bg-slate-700',
        browseIcon: '<i class="icon-image2 position-left"></i> ',
        removeLabel: 'Remove',
        removeClass: 'btn btn-danger',
        removeIcon: '<i class="icon-cancel-square position-left"></i> ',
        uploadClass: 'hidden',
        uploadIcon: '<i class="icon-file-upload position-left"></i> ',
        layoutTemplates: {
            // caption: '<div tabindex="-1" class="form-control file-caption {class}">\n' + '<span class="icon-file-plus kv-caption-icon"></span><div class="file-caption-name"></div>\n' + '</div>'
        },
        initialPreview: ["<img src='{{ asset('storage/'.$logo->icon) }}' class='file-preview-image' alt=''>",],
        overwriteInitial: true,
	});

	$("input[name=logo_white]").fileinput({
    	previewFileType: 'image',
        browseLabel: 'Select',
        browseClass: 'btn bg-slate-700',
        browseIcon: '<i class="icon-image2 position-left"></i> ',
        removeLabel: 'Remove',
        removeClass: 'btn btn-danger',
        removeIcon: '<i class="icon-cancel-square position-left"></i> ',
        uploadClass: 'hidden',
        uploadIcon: '<i class="icon-file-upload position-left"></i> ',
        layoutTemplates: {
            // caption: '<div tabindex="-1" class="form-control file-caption {class}">\n' + '<span class="icon-file-plus kv-caption-icon"></span><div class="file-caption-name"></div>\n' + '</div>'
        },
        initialPreview: ["<img src='{{ asset('storage/'.$logo->logo_white) }}' class='file-preview-image' alt=''>",],
        overwriteInitial: true,
	});
</script>
@endsection

resources/views/admin/config/nav.blade.php
<ul class="nav nav-tabs nav-tabs-highlight">
	<li @if (Request::segment(2) == 'config') class="active" @endif>
		<a href="{{ route('admin.config.edit', $config->id) }}"><i class="icon-magazine position-left"></i> Tentang Website</a>
	</li>
	<li @if (Request::segment(2) == 'seo') class="active" @endif>
		<a href="{{ route('admin.seo.edit', $seo->id) }}"><i class="icon-stats-growth position-left"></i> Seo Website</a>
	</li>
	<li @if (Request::segment(2) == 'contact') class="active" @endif>
		<a href="{{ route('admin.contact.edit', $config->id) }}"><i class="icon-address-book2 position-left"></i> Informasi kontak</a>
	</li>
	<li @if (Request::segment(2) == 'logo') class="active" @endif>
		<a href="{{ route('admin.logo.edit', $config->id) }}"><i class="icon-image4 position-left"></i> Logo</a>
	</li>
	<li @if (Request::segment(2) == 'user') class="active" @endif>
		<a href="{{ route('admin.user.edit', Auth::id()) }}"><i class="icon-user position-left"></i> Akun</a>
	</li>
</ul>