routes/admin.php
<?php

/*
 * Routing khusus admin panel
 */
Route::group(['prefix' => 'administrator', 'middleware' => ['globalvar', 'admin.panel'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('kegiatan-warga/get/images', 'Gallery\GalleryController@getImages')->name('gallery.get.images');
    Route::post('kegiatan-warga/store/images', 'Gallery\GalleryController@storeImages')->name('gallery.store.images');
    Route::post('kegiatan-warga/delete/images', 'Gallery\GalleryController@deleteImages')->name('gallery.delete.images');
    Route::resource('/', 'Dashboard\DashboardController');
    Route::resource('config', 'Config\ConfigController');
    Route::resource('seo', 'Config\SeoController');
    Route::resource('contact', 'Config\ContactController');
    Route::resource('logo', 'Config\LogoController');
    Route::resource('user', 'Config\UserController');
    Route::resource('slider', 'Slider\SliderController');
    Route::resource('kontak', 'ContactUs\ContactUsController')->names([
        'index' => 'contactus.index',
        'create' => 'contactus.create',
        'store' => 'contactus.store',
        'show' => 'contactus.show',
        'edit' => 'contactus.edit',
        'update' => 'contactus.update',
        'destroy' => 'contactus.destroy',
    ])->parameters(['kontak' => 'contactus']);
    Route::resource('produk-warga', 'Merchandise\MerchandiseController')->names([
        'index' => 'merchandise.index',
        'create' => 'merchandise.create',
        'store' => 'merchandise.store',
        'show' => 'merchandise.show',
        'edit' => 'merchandise.edit',
        'update' => 'merchandise.update',
        'destroy' => 'merchandise.destroy',
    ])->parameters(['produk-warga' => 'merchandise']);
    Route::resource('kegiatan-warga', 'Gallery\GalleryController')->names([
        'index' => 'gallery.index',
        'create' => 'gallery.create',
        'store' => 'gallery.store',
        'show' => 'gallery.show',
        'edit' => 'gallery.edit',
        'update' => 'gallery.update',
        'destroy' => 'gallery.destroy',
    ])->parameters(['kegiatan-warga' => 'gallery']);
    Route::resource('berita', 'News\NewsController')->names([
        'index' => 'news.index',
        'create' => 'news.create',
        'store' => 'news.store',
        'show' => 'news.show',
        'edit' => 'news.edit',
        'update' => 'news.update',
        'destroy' => 'news.destroy',
    ])->parameters(['berita' => 'news']);

    Route::resource('informasi', 'Article\ArticleController')->names([
        'index' => 'article.index',
        'create' => 'article.create',
        'store' => 'article.store',
        'show' => 'article.show',
        'edit' => 'article.edit',
        'update' => 'article.update',
        'destroy' => 'article.destroy',
    ])->parameters(['informasi' => 'article']);
    Route::get('informasi/image/get',     'Article\ImageController@getImage')->name('article.get_image');
    Route::post('informasi/image/store',  'Article\ImageController@storeImage')->name('article.store_image');
    Route::post('informasi/image/delete', 'Article\ImageController@deleteImage')->name('article.delete_image');

    Route::get('signout', 'AuthController@signout')->name('signout');
});

Route::group(['prefix' => 'auth', 'namespace' => 'Admin'], function () {
    Route::get('admin', 'AuthController@index')->name('login.admin');
    Route::post('admin', 'AuthController@store')->name('auth.admin');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Frontend', 'as' => 'frontend.', 'middleware' => ['globalvar']], function() {
    Route::get('/', 'Home\HomeController@index')->name('home');
    Route::get('berita', 'News\NewsController@index')->name('news');
    Route::get('berita/{slug}', 'News\NewsController@detail')->name('news.detail');
    Route::get('kegiatan-warga', 'Event\EventController@index')->name('activities');
    Route::get('kegiatan-warga/{slug}', 'Event\EventController@detail')->name('activities.detail');
    Route::get('kontak', 'Contact\ContactController@index')->name('contact');
    Route::get('produk-warga', 'Merchandise\MerchandiseController@index')->name('merchandise');
    Route::get('produk-warga/{slug}', 'Merchandise\MerchandiseController@detail')->name('merchandise.detail');
    Route::get('informasi', 'Information\InformationController@index')->name('informasi');
    Route::get('informasi/{id}', 'Information\InformationController@show')->name('informasi.detail');
    Route::get('cache', function() {
        $artisan = Artisan::call('view:cache');
    	 // $artisan = Artisan::call('migrate');

    	$artisan = Artisan::call('view:clear');
    	echo "Done";
    });
});

resources/views/admin/partials/content.blade.php
<div class="content">

	@yield('content')

</div>

resources/views/admin/partials/navbar.blade.php
	<div class="navbar navbar-default header-highlight">
		<div class="navbar-header">
			<a class="navbar-brand" href="{{ route('admin.index') }}">
				<b class="text-info"><i class="icon-display4"></i>&nbsp; <span>Sistem</span></b><b style="color: white"><span> Administrator</span></b>
			</a>

			<ul class="nav navbar-nav visible-xs-block">
				<li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
				<li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
			</ul>
		</div>

		<div class="navbar-collapse collapse" id="navbar-mobile">
			<ul class="nav navbar-nav">
				<li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>
			</ul>

			<div class="navbar-right">
				<p class="navbar-text">Wellcome back! {{ ucfirst(Auth::user()->name) }}</p>
				<p class="navbar-text"><span class="label bg-success">Online</span></p>
				
				<ul class="nav navbar-nav">				
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="icon-bell2"></i>
							<span class="visible-xs-inline-block position-right">Activity</span>
							<span class="status-mark border-pink-300"></span>
						</a>

						<div class="dropdown-menu dropdown-content">
							<div class="dropdown-content-heading">
								Activity
								<ul class="icons-list">
									<li><a href="#"><i class="icon-menu7"></i></a></li>
								</ul>
							</div>

							<ul class="media-list dropdown-content-body width-350">
								<li class="media">
									<div class="media-left">
										<a href="#" class="btn bg-success-400 btn-rounded btn-icon btn-xs"><i class="icon-mention"></i></a>
									</div>

									<div class="media-body">
										<a href="#">Taylor Swift</a> mentioned you in a post "Angular JS. Tips and tricks"
										<div class="media-annotation">4 minutes ago</div>
									</div>
								</li>

								<li class="media">
									<div class="media-left">
										<a href="#" class="btn bg-pink-400 btn-rounded btn-icon btn-xs"><i class="icon-paperplane"></i></a>
									</div>
									
									<div class="media-body">
										Special offers have been sent to subscribed users by <a href="#">Donna Gordon</a>
										<div class="media-annotation">36 minutes ago</div>
									</div>
								</li>

								<li class="media">
									<div class="media-left">
										<a href="#" class="btn bg-blue btn-rounded btn-icon btn-xs"><i class="icon-plus3"></i></a>
									</div>
									
									<div class="media-body">
										<a href="#">Chris Arney</a> created a new <span class="text-semibold">Design</span> branch in <span class="text-semibold">Limitless</span> repository
										<div class="media-annotation">2 hours ago</div>
									</div>
								</li>

								<li class="media">
									<div class="media-left">
										<a href="#" class="btn bg-purple-300 btn-rounded btn-icon btn-xs"><i class="icon-truck"></i></a>
									</div>
									
									<div class="media-body">
										Shipping cost to the Netherlands has been reduced, database updated
										<div class="media-annotation">Feb 8, 11:30</div>
									</div>
								</li>

								<li class="media">
									<div class="media-left">
										<a href="#" class="btn bg-warning-400 btn-rounded btn-icon btn-xs"><i class="icon-bubble8"></i></a>
									</div>
									
									<div class="media-body">
										New review received on <a href="#">Server side integration</a> services
										<div class="media-annotation">Feb 2, 10:20</div>
									</div>
								</li>

								<li class="media">
									<div class="media-left">
										<a href="#" class="btn bg-teal-400 btn-rounded btn-icon btn-xs"><i class="icon-spinner11"></i></a>
									</div>
									
									<div class="media-body">
										<strong>January, 2016</strong> - 1320 new users, 3284 orders, $49,390 revenue
										<div class="media-annotation">Feb 1, 05:46</div>
									</div>
								</li>
							</ul>
						</div>
					</li>
					<li><a href="{{ route('admin.signout') }}"><i class="icon-switch2"></i></a></li>				
				</ul>
			</div>
		</div>
	</div>

resources/views/admin/partials/script.blade.php
<!-- Core JS files -->
<script type="text/javascript" src="{{asset('admin/js/plugins/loaders/pace.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('admin/js/core/libraries/jquery.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('admin/js/core/libraries/bootstrap.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('admin/js/plugins/loaders/blockui.min.js')}}"></script>
	<script type="text/javascript" src="{{ asset('js/sweetalert2.min.js') }}"></script>
	<!-- /core JS files -->

	<!-- Theme JS files -->
	<script type="text/javascript" src="{{asset('admin/js/plugins/visualization/d3/d3.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('admin/js/plugins/visualization/d3/d3_tooltip.js')}}"></script>
	<script type="text/javascript" src="{{asset('admin/js/plugins/forms/styling/switchery.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('admin/js/plugins/forms/styling/uniform.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('admin/js/plugins/forms/selects/bootstrap_multiselect.js')}}"></script>
	<script type="text/javascript" src="{{asset('admin/js/plugins/ui/moment/moment.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('admin/js/plugins/pickers/daterangepicker.js')}}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/validation/validate.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/selects/bootstrap_multiselect.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/inputs/touchspin.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/selects/select2.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/styling/switch.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/styling/switchery.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/forms/styling/uniform.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/ckeditor/ckeditor.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/uploaders/fileinput.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('admin/js/plugins/notifications/pnotify.min.js') }}"></script>
	@yield('min-js')

	<script type="text/javascript" src="{{asset('admin/js/core/app.js')}}"></script>
	@yield('js')

	<script type="text/javascript" src="{{asset('admin/js/plugins/ui/ripple.min.js')}}"></script>
	<!-- /theme JS files -->

resources/views/admin/partials/sidebar.blade.php
<div class="sidebar sidebar-main">
	<div class="sidebar-content">

		<!-- User menu -->
		<div class="sidebar-user-material">
			<div class="category-content">
				<div class="sidebar-user-material-content">
					<a href="#"><img src="{{ asset('admin/images/avatar-1.png') }}" class="img-circle img-responsive" alt=""></a>
					<h6>{{ ucwords(Auth::user()->name) }}</h6>
					<span class="text-size-small">{{ ucwords(Auth::user()->permition) }}</span>
				</div>

				<div class="sidebar-user-material-menu">
					<a href="#user-nav" data-toggle="collapse"><span>My account</span> <i class="caret"></i></a>
				</div>
			</div>

			<div class="navigation-wrapper collapse" id="user-nav">
				<ul class="navigation">
					<li><a href="#"><i class="icon-user-plus"></i> <span>My profile</span></a></li>
					<li><a href="#"><i class="icon-coins"></i> <span>My balance</span></a></li>
					<li><a href="#"><i class="icon-comment-discussion"></i> <span><span class="badge bg-teal-400 pull-right">58</span> Messages</span></a></li>
					<li class="divider"></li>
					<li><a href="#"><i class="icon-cog5"></i> <span>Account settings</span></a></li>
					<li><a href="{{ route('admin.signout') }}"><i class="icon-switch2"></i> <span>Logout</span></a></li>
				</ul>
			</div>
		</div>
		<!-- /user menu -->


		<!-- Main navigation -->
		<div class="sidebar-category sidebar-category-visible">
			<div class="category-content no-padding">
				<ul class="navigation navigation-main navigation-accordion">

					<!-- Main -->
					<li class="navigation-header"><span>Menu &nbsp;<i class="icon-menu" title="Main pages"></i></span></li>
					<li @if(Request::segment(2) == null) class="active" @endif><a href="{{route('admin.index')}}"><i class="icon-home4"></i> <span>Dashboard</span></a></li>
					<li @if (Request::segment(2) == 'merchandise') class="active" @endif>
						<a href="{{ route('admin.merchandise.index') }}"><i class="icon-basket"></i> <span>Produk Warga</span></a>
                    </li>
					<li @if (Request::segment(2) == 'gallery') class="active" @endif>
						<a href="{{ route('admin.gallery.index') }}"><i class="icon-shutter"></i> <span>Kegiatan Warga</span></a>
                    </li>
                    <li @if (Request::segment(2) == 'news' ) class="active" @endif>
                        <a href="{{ route('admin.news.index') }}"><i class="icon-newspaper"></i> <span>Berita</span></a>
                    </li>
                    <li @if (Request::segment(2) == 'informasi' ) class="active" @endif>
                    	<a href="{{ route('admin.article.index') }}"><i class="icon-search4"></i> Informasi</a>
                    </li>
					<li @if (Request::segment(2) == 'contactus') class="active" @endif>
						<a href="{{ route('admin.contactus.index') }}"><i class="icon-address-book"></i> <span>Kontak</span></a>
					</li>
					<li @if(Request::segment(2) == 'slider') class="active" @endif>
						<a href="{{ route('admin.slider.index') }}"><i class="icon-image-compare"></i> <span>Slider</span></a>
					</li>
					<li @if(Request::segment(2) == 'config') class="active" @elseif(Request::segment(2) == 'seo') class="active" @elseif(Request::segment(2) == 'contact') class="active" @elseif(Request::segment(2) == 'user') class="active" @elseif(Request::segment(2) == 'logo') class="active" @endif><a href="{{route('admin.config.edit', 1)}}"><i class="icon-cog3"></i> <span>Pengaturan</span></a></li>
				</ul>
			</div>
		</div>
		<!-- /main navigation -->

	</div>
</div>

resources/views/admin/partials/style.blade.php
<!-- Global stylesheets -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
<link href="{{asset('admin/css/icons/icomoon/styles.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('admin/css/bootstrap.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('admin/css/core.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('admin/css/components.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('admin/css/colors.css')}}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{{ asset('js/sweetalert2.min.css') }}">
  {{-- <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8/dist/sweetalert2.min.js"></script> --}}
  {{-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@8/dist/sweetalert2.min.css" id="theme-styles"> --}}
    <!-- /global stylesheets -->
    @yield('css')